"""empty message

Revision ID: 53e1f7ccae8b
Revises: b794c48cfc15
Create Date: 2019-04-23 18:49:23.153013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53e1f7ccae8b'
down_revision = 'b794c48cfc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('father_id', sa.Integer(), nullable=True))
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['father_id'], ['id'])
    op.drop_column('category', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_ibfk_1', 'category', 'category', ['category_id'], ['id'])
    op.drop_column('category', 'father_id')
    # ### end Alembic commands ###
