"""empty message

Revision ID: 8ad17808e205
Revises: 53e1f7ccae8b
Create Date: 2019-04-23 19:27:53.767702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ad17808e205'
down_revision = '53e1f7ccae8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatherc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category', sa.Column('fatherc_id', sa.Integer(), nullable=True))
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'fatherc', ['fatherc_id'], ['id'])
    op.drop_column('category', 'father_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('father_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_ibfk_1', 'category', 'category', ['father_id'], ['id'])
    op.drop_column('category', 'fatherc_id')
    op.drop_table('fatherc')
    # ### end Alembic commands ###
